fragment PostParts on Post {
  title
  body
  pubDate
  coverImage
  coverImageAlt
  tags
  draft
}

fragment WorkParts on Work {
  title
  body
}

fragment StaticParts on Static {
  title
  body
}

fragment UpcomingParts on Upcoming {
  title
  description
  status
}
